"""``conversat init`` -- scaffold a starter suite."""

from __future__ import annotations

from pathlib import Path
from typing import Annotated, Any

import typer
import yaml

from conversat.cli.common import Option, console_for, write_text_file
from conversat.engine.loader import suite_from_dict
from conversat.models.suite import ConnectorConfig

CONNECTOR_PRESETS: dict[str, ConnectorConfig] = {
    "http": ConnectorConfig(
        type="http",
        config={
            "url": "http://127.0.0.1:8099/chat",
            "method": "POST",
            "json_body": {"message": "{{text}}", "user": "{{vars.user}}"},
            "response_text_path": "reply",
            "timeout": 15,
        },
    ),
    "websocket": ConnectorConfig(
        type="websocket",
        config={
            "url": "ws://127.0.0.1:8099/ws/chat",
            "request_template": '{"message": "{{text}}"}',
            "response_text_path": "reply",
            "timeout": 15,
        },
    ),
    "web": ConnectorConfig(
        type="web",
        config={
            "base_url": "http://127.0.0.1:3000",
            "input_selector": "#chat-input",
            "message_selector": "[data-conversat-msg]",
            "timeout": 20,
        },
    ),
    "echo": ConnectorConfig(type="echo", config={"prefix": "echo: "}),
    "scripted": ConnectorConfig(
        type="scripted", config={"replies": ["hello from the scripted bot", "anything else?"]}
    ),
}

HEADER = """\
# conversat suite -- https://github.com/conversat-dev/conversat
# Docs: assert `contains`, `matches`, `json_path`, `response_time_under`, `any_of`, ...
# Run it with: conversat run {filename}
"""


def starter_payload(connector_type: str, filename: str) -> dict[str, Any]:
    """The starter suite as a plain dict (always validates)."""
    return {
        "name": "smoke",
        "description": "Starter suite generated by 'conversat init'",
        "connector": CONNECTOR_PRESETS[connector_type].model_dump(mode="json"),
        "defaults": {
            "timeout": 20,
            "tags": ["smoke"],
            "variables": {"user": "tester"},
        },
        "cases": [
            {
                "name": "greeting",
                "description": "The bot answers a greeting",
                "tags": ["chat"],
                "steps": [
                    {
                        "send": "Hello there!",
                        "expect": [
                            {"not_empty": True},
                            {"contains_any": ["hello", "hi", "hey"]},
                        ],
                    }
                ],
            },
            {
                "name": "math",
                "description": "Arithmetic is answered correctly",
                "tags": ["logic"],
                "steps": [
                    {
                        "send": "What is 3 + 4?",
                        "expect": [
                            {"type": "contains", "value": "7"},
                            {"type": "response_time_under", "value": 5000},
                        ],
                    }
                ],
            },
            {
                "name": "multi-turn",
                "description": "The bot remembers earlier turns",
                "tags": ["memory"],
                "setup": [
                    {"send": "My name is Ada", "expect": [{"not_empty": True}]}
                ],
                "steps": [
                    {
                        "send": "What is my name?",
                        "expect": [
                            {"type": "matches", "pattern": "(?i)\\bada\\b"},
                            {"type": "not_contains", "value": "who are you"},
                        ],
                    }
                ],
            },
        ],
        "metadata": {"generated_by": "conversat init"},
    }


def register(app: typer.Typer) -> None:
    @app.command("init")
    def init_suite(
        path: Annotated[
            Path,
            Option("--path", "-p", help="Where to write the suite (default: ./conversat-suite.yaml)."),
        ] = Path("conversat-suite.yaml"),
        connector_type: Annotated[
            str, Option("--connector", "-c", help="http, websocket, web, echo or scripted.")
        ] = "http",
        force: Annotated[bool, Option("--force", help="Overwrite an existing file.")] = False,
    ) -> None:
        """Create a starter test suite in the current directory."""
        console = console_for()
        connector_type = connector_type.strip().lower()
        if connector_type not in CONNECTOR_PRESETS:
            console.print(
                f"[red]unknown connector {connector_type!r}[/red]; "
                f"choose one of: {', '.join(CONNECTOR_PRESETS)}",
                stderr=True,
            )
            raise typer.Exit(code=2)

        payload = starter_payload(connector_type, path.name)
        content = HEADER.format(filename=path.name) + yaml.safe_dump(
            payload, sort_keys=False, allow_unicode=True, width=100
        )

        try:
            written = write_text_file(path, content, overwrite=force)
        except typer.BadParameter as exc:
            console.print(f"[red]{exc}[/red]", stderr=True)
            raise typer.Exit(code=2) from exc

        suite = suite_from_dict(payload)
        console.print(
            f"[green]created[/green] {written} "
            f"({len(suite.cases)} cases, connector: [magenta]{connector_type}[/magenta])"
        )
        console.print(f"next: [cyan]conversat run {written}[/cyan]")
